### ISSUE TITLE
What is this other lock used for in the ant.plus code?

### ISSUE THREAD

**Issue by David-Hari** [mch/python-ant#9]
There is a lock used in the method [`HeartRate.processData`](https://github.com/mch/python-ant/blob/221185b4d4511281f44f9f35763a2f1410ae1262/src/ant/plus/heartrate.py#L77). That method is invoked (indirectly, through `DeviceProfile.process`) by the channel as a callback when it processes a message.
The channel also uses a lock - [`evmCallbackLock`](https://github.com/mch/python-ant/blob/master/src/ant/core/node.py#L180) - when calling the callback.
Furthermore, that `evmCallbackLock` is used by the `EventPump` thread when it processes each message.

Now, I'm not entirely sure of how or why the `evmCallbackLock` is used, but I don't understand why yet another lock is needed by the ant plus code.
Could you explain?

**Comment by mch** [comment]
I haven't investigated the channel lock much. The reason I put a lock in HeartRate originally was because when I first wrote it there was no callback. The client essentially had to poll, or could poll, for heart rate data  by calling the property. In a web server, or in many other applications, this almost certainly occurs on a separate thread. So the lock protects against concurrently reading and writing a value within the heartrate object. Something that is probably extremely unlikely, but possible. I didn't research if the computed heart rate could be updated atomically; if it is, the lock is likely unnecessary.

**Comment by David-Hari** [comment]
Well I just think it's unnecessary because there is already a lock (`evmCallbackLock`), so I wouldn't have thought you'd need another one. I'll have to read up on how locks work in Python (and just in general, it's been a while since I've written multi-threaded code).

**Comment by mch** [comment]
The reason the HeartRate one is needed in addition to the channel one is because the channel one cannot protect read access to `self._computed_heart_rate`. See [line 124](https://github.com/mch/python-ant/blob/221185b4d4511281f44f9f35763a2f1410ae1262/src/ant/plus/heartrate.py#L124).

**Comment by David-Hari** [comment]
Yes, I see that, and I imagine the same pattern should be done for access to other variables (i.e. in power.py).
What about it's use in `processData`? Is that still needed?

**Comment by David-Hari** [comment]
Of course, it needs to lock when it writes the data.
Do you think we should just do away with the lock and the property accessors and just provide the data in the callback? Or do you think it's still worth having them? It depends on whether people are likely to do stuff in the callback or whether they would do polling from another thread.
